export const MovieTitle = [
  "The Avengers", "Inception", "Interstellar", "The Dark Knight", "Fight Club",
  "Forrest Gump", "Titanic", "The Matrix", "Gladiator", "Pulp Fiction",
  "Shutter Island", "Avengers: Endgame", "Avatar", "The Wolf of Wall Street",
  "The Godfather", "The Shawshank Redemption", "The Social Network", "Parasite",
  "The Prestige", "Django Unchained", "Joker", "Whiplash", "The Lion King",
  "Toy Story", "Black Panther", "Iron Man", "Doctor Strange",
  "Guardians of the Galaxy", "No Country for Old Men", "The Truman Show",
  "The Departed", "Wednesday", "Thor", "Captain Marvel", "Captain America: Civil War",
  "Logan", "Deadpool", "Ant-Man", "Spider-Man: Homecoming", "Spider-Man: No Way Home",
  "The Batman", "The Irishman", "The Revenant", "The Hateful Eight", "Tenet",
  "Oppenheimer", "Barbie", "Everything Everywhere All At Once", "1917",
  "The Big Short", "The Imitation Game", "La La Land", "Knives Out", "Dune",
  "The Hunger Games", "Catching Fire", "Divergent", "Insurgent", "The Maze Runner",
  "The Fault in Our Stars", "Me Before You", "The Theory of Everything", "Bohemian Rhapsody",
  "Rocketman", "A Star is Born", "Interstellar", "Gravity", "Life of Pi",
  "The Curious Case of Benjamin Button", "The Great Gatsby", "Now You See Me",
  "The Conjuring", "Annabelle", "Insidious", "Hereditary", "Midsommar", "Get Out",
  "Us", "Nope", "Bird Box", "The Nun", "It", "It Chapter Two", "Ready Player One",
  "Pacific Rim", "Edge of Tomorrow", "World War Z", "I Am Legend", "Mad Max: Fury Road",
  "Transformers", "Transformers: Age of Extinction", "The Lego Movie", "Frozen",
  "Zootopia", "Moana", "Coco", "Soul", "Encanto", "Turning Red", "Ratatouille",
  "Up", "Inside Out", "Finding Nemo", "Finding Dory"
];
